resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: git                       # <-- replace with your integration
      path: SaiKUndurthi/jfrog-pipelines-docker-sample    # <-- replace with your repository name
      branches:
        include: master

  - name: dbp_image
    type: Image
    configuration:
      registry: dockert                                # <-- replace with your artifactory integration
      sourceRepository: a-docker               # <-- required if registry is Artifactory
      imageName: mcr.microsoft.com/dotnet/framework/sdk  # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: dbp_build
      buildNumber: 1    

  - name: dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: dbp_build
      buildNumber: 1
      

pipelines:
  - name: pipeline_dbp
    steps:
      - name: power_buld
        type: PowerShell
        #configuration:
         # runtime:
          #  type: image
           # image:
            #  custom:
             #   name: testshani.jfrog.io/mcr/dotnet/framework/sdk
              #  tag: 	4.7.2
#                autoPull: true                          # <-- replace with your artifactory integration
        execution:
          onStart:
            - echo "Testing"
          onExecute:
            - echo "msbuild"
            - dotnet
